name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (optional, e.g., -hotfix, -beta)'
        required: false
        default: ''
      release_notes:
        description: 'Release notes'
        required: true
        default: 'Manual release'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

jobs:
  manual-release:
    name: Manual Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew testDebugUnitTest --stacktrace
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Generate version number
      id: version
      run: |
        VERSION=$(date +'%Y%m%d')${{ github.event.inputs.version_suffix }}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: WorkRec v${{ steps.version.outputs.version }}
        body: |
          ## WorkRec Manual Release v${{ steps.version.outputs.version }}
          
          **Branch:** ${{ github.ref_name }}
          **Commit:** ${{ github.sha }}
          **Build Date:** $(date +'%Y-%m-%d %H:%M:%S UTC')
          
          ### Release Notes
          ${{ github.event.inputs.release_notes }}
          
          ### Installation
          Download the APK file below and install on your Android device.
          
          **Note:** You may need to enable "Install from unknown sources" in your device settings.
        draft: false
        prerelease: ${{ contains(github.event.inputs.version_suffix, 'beta') || contains(github.event.inputs.version_suffix, 'alpha') }}
        
    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release.apk
        asset_name: WorkRec-v${{ steps.version.outputs.version }}.apk
        asset_content_type: application/vnd.android.package-archive